name: Run
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Run:
    if: startsWith(github.head_ref, 'tagpr-from-') == false && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - run: go run *.go
